// Code generated by goyacc -o calc.go -p Calc calc.y. DO NOT EDIT.

//line calc.y:8

package calc

import __yyfmt__ "fmt"

//line calc.y:9

import (
	"fmt"
)

// keep variables
var regs = make(map[string]interface{}, 26)

// calculate
var base int

// unit test
type Test struct {
	node  string
	value []interface{}
}

//line calc.y:31
type CalcSymType struct {
	yys         int
	val         int
	str         string
	slice       []int
	twoDslice   [][]int
	threeDslice [][][]int
	iface       interface{}
	test        Test
}

const DIGIT = 57346
const LETTER = 57347
const THIRDCOMMA = 57348
const SECONDCOMMA = 57349
const FIRSTCOMMA = 57350
const UMINUS = 57351

var CalcToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"DIGIT",
	"LETTER",
	"'|'",
	"'&'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'='",
	"'\\n'",
	"'['",
	"']'",
	"','",
	"THIRDCOMMA",
	"SECONDCOMMA",
	"FIRSTCOMMA",
	"UMINUS",
	"'?'",
	"'('",
	"')'",
	"'A'",
	"'S'",
	"'K'",
}

var CalcStatenames = [...]string{}

const CalcEofCode = 1
const CalcErrCode = 2
const CalcInitialStackSize = 16

//line calc.y:304
/*  start  of  programs  */
//line yacctab:1
var CalcExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const CalcPrivate = 57344

const CalcLast = 124

var CalcAct = [...]int8{
	15, 5, 68, 40, 9, 12, 47, 18, 25, 26,
	27, 20, 20, 8, 24, 67, 17, 17, 45, 44,
	49, 42, 43, 19, 52, 46, 45, 44, 49, 18,
	16, 16, 53, 56, 57, 58, 59, 60, 61, 62,
	63, 41, 64, 65, 66, 70, 23, 35, 6, 37,
	36, 49, 34, 33, 28, 29, 30, 31, 32, 54,
	23, 20, 8, 55, 49, 71, 17, 20, 8, 20,
	69, 51, 19, 20, 41, 20, 39, 38, 21, 48,
	16, 48, 14, 20, 27, 48, 50, 48, 34, 33,
	28, 29, 30, 31, 32, 23, 33, 28, 29, 30,
	31, 32, 20, 8, 3, 2, 72, 28, 29, 30,
	31, 32, 23, 27, 30, 31, 32, 1, 7, 4,
	22, 11, 10, 13,
}

var CalcPact = [...]int16{
	57, 64, -1000, -1000, -1000, 107, -1000, 98, -1000, 82,
	39, -1000, 33, 60, -23, 70, 7, 7, 2, 71,
	-1000, -1000, 8, -1000, 10, 37, 41, 65, 7, 7,
	7, 7, 7, 7, 7, 25, -5, -1000, 0, -1000,
	-25, -1000, 46, -1000, 79, -1000, 33, 2, -1000, 70,
	69, -1000, 55, -1000, -1000, -1000, 104, 104, -1000, -1000,
	-1000, 99, 89, 63, 2, -1000, -1000, -5, -1000, -1000,
	70, 90, -1000,
}

var CalcPgo = [...]int8{
	0, 1, 0, 4, 6, 5, 123, 48, 122, 121,
	119, 118, 117, 105, 104,
}

var CalcR1 = [...]int8{
	0, 12, 12, 12, 12, 12, 13, 14, 10, 10,
	10, 7, 7, 7, 7, 7, 8, 8, 8, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 9,
	6, 6, 6, 5, 5, 5, 4, 4, 4, 4,
	2, 2, 1, 1, 11,
}

var CalcR2 = [...]int8{
	0, 0, 2, 1, 1, 1, 3, 1, 3, 3,
	3, 1, 1, 1, 1, 1, 1, 5, 3, 1,
	3, 3, 3, 3, 3, 3, 3, 3, 2, 1,
	2, 3, 2, 2, 3, 2, 2, 2, 3, 2,
	1, 2, 1, 2, 3,
}

var CalcChk = [...]int16{
	-1000, -12, -13, -14, -10, -1, -7, -11, 5, -3,
	-8, -9, -5, -6, 25, -2, 23, 9, -4, 15,
	4, 14, 13, 5, -4, -2, -1, 15, 8, 9,
	10, 11, 12, 7, 6, 8, 17, 16, 17, 16,
	26, 4, -3, -3, 17, 16, -5, -4, 16, -2,
	15, -7, -1, 22, 22, 22, -3, -3, -3, -3,
	-3, -3, -3, 15, -4, -4, -5, 15, 27, 24,
	-2, -1, 16,
}

var CalcDef = [...]int8{
	1, -2, 3, 4, 5, 29, 7, 0, 42, 11,
	12, 13, 14, 15, 0, 19, 0, 0, 16, 0,
	40, 2, 0, 43, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 35, 0, 32,
	0, 41, 0, 28, 0, 39, 30, 33, 36, 37,
	0, 6, 29, 8, 9, 10, 21, 22, 23, 24,
	25, 26, 27, 0, 18, 34, 31, 0, 44, 20,
	38, 0, 17,
}

var CalcTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	14, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 12, 7, 3,
	23, 24, 10, 8, 17, 9, 3, 11, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 13, 3, 22, 3, 25, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 27, 3, 3, 3, 3,
	3, 3, 3, 26, 3, 3, 3, 3, 3, 3,
	3, 15, 3, 16, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 6,
}

var CalcTok2 = [...]int8{
	2, 3, 4, 5, 18, 19, 20, 21,
}

var CalcTok3 = [...]int8{
	0,
}

var CalcErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	CalcDebug        = 0
	CalcErrorVerbose = false
)

type CalcLexer interface {
	Lex(lval *CalcSymType) int
	Error(s string)
}

type CalcParser interface {
	Parse(CalcLexer) int
	Lookahead() int
}

type CalcParserImpl struct {
	lval  CalcSymType
	stack [CalcInitialStackSize]CalcSymType
	char  int
}

func (p *CalcParserImpl) Lookahead() int {
	return p.char
}

func CalcNewParser() CalcParser {
	return &CalcParserImpl{}
}

const CalcFlag = -1000

func CalcTokname(c int) string {
	if c >= 1 && c-1 < len(CalcToknames) {
		if CalcToknames[c-1] != "" {
			return CalcToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func CalcStatname(s int) string {
	if s >= 0 && s < len(CalcStatenames) {
		if CalcStatenames[s] != "" {
			return CalcStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func CalcErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !CalcErrorVerbose {
		return "syntax error"
	}

	for _, e := range CalcErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + CalcTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(CalcPact[state])
	for tok := TOKSTART; tok-1 < len(CalcToknames); tok++ {
		if n := base + tok; n >= 0 && n < CalcLast && int(CalcChk[int(CalcAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if CalcDef[state] == -2 {
		i := 0
		for CalcExca[i] != -1 || int(CalcExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; CalcExca[i] >= 0; i += 2 {
			tok := int(CalcExca[i])
			if tok < TOKSTART || CalcExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if CalcExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += CalcTokname(tok)
	}
	return res
}

func Calclex1(lex CalcLexer, lval *CalcSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(CalcTok1[0])
		goto out
	}
	if char < len(CalcTok1) {
		token = int(CalcTok1[char])
		goto out
	}
	if char >= CalcPrivate {
		if char < CalcPrivate+len(CalcTok2) {
			token = int(CalcTok2[char-CalcPrivate])
			goto out
		}
	}
	for i := 0; i < len(CalcTok3); i += 2 {
		token = int(CalcTok3[i+0])
		if token == char {
			token = int(CalcTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(CalcTok2[1]) /* unknown char */
	}
	if CalcDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", CalcTokname(token), uint(char))
	}
	return char, token
}

func CalcParse(Calclex CalcLexer) int {
	return CalcNewParser().Parse(Calclex)
}

func (Calcrcvr *CalcParserImpl) Parse(Calclex CalcLexer) int {
	var Calcn int
	var CalcVAL CalcSymType
	var CalcDollar []CalcSymType
	_ = CalcDollar // silence set and not used
	CalcS := Calcrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Calcstate := 0
	Calcrcvr.char = -1
	Calctoken := -1 // Calcrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Calcstate = -1
		Calcrcvr.char = -1
		Calctoken = -1
	}()
	Calcp := -1
	goto Calcstack

ret0:
	return 0

ret1:
	return 1

Calcstack:
	/* put a state and value onto the stack */
	if CalcDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", CalcTokname(Calctoken), CalcStatname(Calcstate))
	}

	Calcp++
	if Calcp >= len(CalcS) {
		nyys := make([]CalcSymType, len(CalcS)*2)
		copy(nyys, CalcS)
		CalcS = nyys
	}
	CalcS[Calcp] = CalcVAL
	CalcS[Calcp].yys = Calcstate

Calcnewstate:
	Calcn = int(CalcPact[Calcstate])
	if Calcn <= CalcFlag {
		goto Calcdefault /* simple state */
	}
	if Calcrcvr.char < 0 {
		Calcrcvr.char, Calctoken = Calclex1(Calclex, &Calcrcvr.lval)
	}
	Calcn += Calctoken
	if Calcn < 0 || Calcn >= CalcLast {
		goto Calcdefault
	}
	Calcn = int(CalcAct[Calcn])
	if int(CalcChk[Calcn]) == Calctoken { /* valid shift */
		Calcrcvr.char = -1
		Calctoken = -1
		CalcVAL = Calcrcvr.lval
		Calcstate = Calcn
		if Errflag > 0 {
			Errflag--
		}
		goto Calcstack
	}

Calcdefault:
	/* default state action */
	Calcn = int(CalcDef[Calcstate])
	if Calcn == -2 {
		if Calcrcvr.char < 0 {
			Calcrcvr.char, Calctoken = Calclex1(Calclex, &Calcrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if CalcExca[xi+0] == -1 && int(CalcExca[xi+1]) == Calcstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Calcn = int(CalcExca[xi+0])
			if Calcn < 0 || Calcn == Calctoken {
				break
			}
		}
		Calcn = int(CalcExca[xi+1])
		if Calcn < 0 {
			goto ret0
		}
	}
	if Calcn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Calclex.Error(CalcErrorMessage(Calcstate, Calctoken))
			Nerrs++
			if CalcDebug >= 1 {
				__yyfmt__.Printf("%s", CalcStatname(Calcstate))
				__yyfmt__.Printf(" saw %s\n", CalcTokname(Calctoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Calcp >= 0 {
				Calcn = int(CalcPact[CalcS[Calcp].yys]) + CalcErrCode
				if Calcn >= 0 && Calcn < CalcLast {
					Calcstate = int(CalcAct[Calcn]) /* simulate a shift of "error" */
					if int(CalcChk[Calcstate]) == CalcErrCode {
						goto Calcstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if CalcDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", CalcS[Calcp].yys)
				}
				Calcp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if CalcDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", CalcTokname(Calctoken))
			}
			if Calctoken == CalcEofCode {
				goto ret1
			}
			Calcrcvr.char = -1
			Calctoken = -1
			goto Calcnewstate /* try again in the same state */
		}
	}

	/* reduction by production Calcn */
	if CalcDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Calcn, CalcStatname(Calcstate))
	}

	Calcnt := Calcn
	Calcpt := Calcp
	_ = Calcpt // guard against "declared and not used"

	Calcp -= int(CalcR2[Calcn])
	// Calcp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Calcp+1 >= len(CalcS) {
		nyys := make([]CalcSymType, len(CalcS)*2)
		copy(nyys, CalcS)
		CalcS = nyys
	}
	CalcVAL = CalcS[Calcp+1]

	/* consult goto table to find next state */
	Calcn = int(CalcR1[Calcn])
	Calcg := int(CalcPgo[Calcn])
	Calcj := Calcg + CalcS[Calcp].yys + 1

	if Calcj >= CalcLast {
		Calcstate = int(CalcAct[Calcg])
	} else {
		Calcstate = int(CalcAct[Calcj])
		if int(CalcChk[Calcstate]) != -Calcn {
			Calcstate = int(CalcAct[Calcg])
		}
	}
	// dummy call; replaced with literal code
	switch Calcnt {

	case 5:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:77
		{
			setResult(Calclex, CalcDollar[1].test)
		}
	case 6:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:84
		{
			regs[CalcDollar[1].str] = CalcDollar[3].iface
		}
	case 7:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:91
		{
			fmt.Println(CalcDollar[1].iface)
		}
	case 8:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:98
		{
			CalcVAL.test.node = "array"
			CalcVAL.test.value = append(CalcVAL.test.value, CalcDollar[2].slice)
		}
	case 9:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:103
		{
			CalcVAL.test.node = "number"
			CalcVAL.test.value = append(CalcVAL.test.value, CalcDollar[2].val)
		}
	case 10:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:108
		{
			CalcVAL.test.node = "variable"
			CalcVAL.test.value = append(CalcVAL.test.value, CalcDollar[2].str)
		}
	case 11:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:116
		{
			setResult(Calclex, CalcDollar[1].val)
			CalcVAL.iface = CalcDollar[1].val
		}
	case 12:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:121
		{
			setResult(Calclex, CalcDollar[1].iface)
			CalcVAL.iface = CalcDollar[1].iface
		}
	case 13:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:126
		{
			setResult(Calclex, CalcDollar[1].iface)
			CalcVAL.iface = CalcDollar[1].iface
		}
	case 14:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:132
		{
			CalcVAL.iface = CalcDollar[1].twoDslice
		}
	case 15:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:136
		{
			CalcVAL.iface = CalcDollar[1].threeDslice
		}
	case 16:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:143
		{
			CalcVAL.iface = CalcDollar[1].slice
		}
	case 17:
		CalcDollar = CalcS[Calcpt-5 : Calcpt+1]
//line calc.y:147
		{
			tmp := make([]int, len(CalcDollar[1].iface.([]int)))
			for i := 0; i < len(CalcDollar[1].iface.([]int)); i++ {
				tmp[i] = CalcDollar[1].iface.([]int)[i] + regs[CalcDollar[4].str].([]int)[i]
			}
			CalcVAL.iface = tmp
		}
	case 18:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:155
		{
			tmp := make([]int, len(CalcDollar[1].iface.([]int)))
			for i := 0; i < len(CalcDollar[1].iface.([]int)); i++ {
				tmp[i] = CalcDollar[1].iface.([]int)[i] + CalcDollar[3].slice[i]
			}
			CalcVAL.iface = tmp
		}
	case 19:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:166
		{
			CalcVAL.val = CalcDollar[1].val
		}
	case 20:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:170
		{
			CalcVAL.val = CalcDollar[2].val
		}
	case 21:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:174
		{
			CalcVAL.val = CalcDollar[1].val + CalcDollar[3].val
		}
	case 22:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:178
		{
			CalcVAL.val = CalcDollar[1].val - CalcDollar[3].val
		}
	case 23:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:182
		{
			CalcVAL.val = CalcDollar[1].val * CalcDollar[3].val
		}
	case 24:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:186
		{
			CalcVAL.val = CalcDollar[1].val / CalcDollar[3].val
		}
	case 25:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:190
		{
			CalcVAL.val = CalcDollar[1].val % CalcDollar[3].val
		}
	case 26:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:194
		{
			CalcVAL.val = CalcDollar[1].val & CalcDollar[3].val
		}
	case 27:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:198
		{
			CalcVAL.val = CalcDollar[1].val | CalcDollar[3].val
		}
	case 28:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:202
		{
			CalcVAL.val = -CalcDollar[2].val
		}
	case 29:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:209
		{
			CalcVAL.iface = regs[CalcDollar[1].str]
		}
	case 30:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:217
		{
			CalcVAL.threeDslice = append(CalcVAL.threeDslice, CalcDollar[2].twoDslice)
		}
	case 31:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:221
		{
			CalcVAL.threeDslice = append(CalcVAL.threeDslice, CalcDollar[3].twoDslice)
		}
	case 32:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:225
		{
			CalcVAL.threeDslice = CalcDollar[1].threeDslice
		}
	case 33:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:233
		{
			CalcVAL.twoDslice = append(CalcVAL.twoDslice, CalcDollar[2].slice)
		}
	case 34:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:237
		{
			CalcVAL.twoDslice = append(CalcVAL.twoDslice, CalcDollar[3].slice)
		}
	case 35:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:241
		{
			CalcVAL.twoDslice = CalcDollar[1].twoDslice
		}
	case 36:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:250
		{
			CalcVAL.slice = []int{}
		}
	case 37:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:254
		{
			CalcVAL.slice = append(CalcVAL.slice, CalcDollar[2].val)
		}
	case 38:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:258
		{
			CalcVAL.slice = append(CalcVAL.slice, CalcDollar[3].val)
		}
	case 39:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:262
		{
			CalcVAL.slice = CalcDollar[1].slice
		}
	case 40:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:271
		{
			CalcVAL.val = CalcDollar[1].val
			if CalcDollar[1].val == 0 {
				base = 8
			} else {
				base = 10
			}
		}
	case 41:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:280
		{
			CalcVAL.val = base*CalcDollar[1].val + CalcDollar[2].val
		}
	case 42:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:292
		{
			CalcVAL.str = fmt.Sprintf("%c", CalcDollar[1].val)
		}
	case 43:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:296
		{
			CalcVAL.str = CalcDollar[1].str + fmt.Sprintf("%c", CalcDollar[2].val)
		}
	case 44:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:302
		{
		}
	}
	goto Calcstack /* stack new state and value */
}
