// Code generated by goyacc -o calc.go -p Calc calc.y. DO NOT EDIT.

//line calc.y:8

package main

import __yyfmt__ "fmt"

//line calc.y:9

import (
	"bufio"
	"fmt"
	"os"
	"unicode"
)

// a number
var regs = make([]int, 26)

// one dimensional
var arrayMap = make(map[int][]int)

// two dimensionals
var arrayMap2 = make(map[int][][]int)

// three dimensionals
var arrayMap3 = make(map[int][][][]int)

// calculate
var base int

//line calc.y:37
type CalcSymType struct {
	yys         int
	val         int
	slice       []int
	twoDslice   [][]int
	threeDslice [][][]int
}

const DIGIT = 57346
const LETTER = 57347
const UMINUS = 57348

var CalcToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"DIGIT",
	"LETTER",
	"'|'",
	"'&'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UMINUS",
	"'\\n'",
	"'='",
	"'['",
	"']'",
	"'('",
	"')'",
	"','",
}

var CalcStatenames = [...]string{}

const CalcEofCode = 1
const CalcErrCode = 2
const CalcInitialStackSize = 16

//line calc.y:177
/*  start  of  programs  */

type CalcLex struct {
	s   string
	pos int
}

func (l *CalcLex) Lex(lval *CalcSymType) int {
	var c rune = ' '
	for c == ' ' {
		if l.pos == len(l.s) {
			return 0
		}
		c = rune(l.s[l.pos])
		l.pos += 1
	}

	if unicode.IsDigit(c) {
		lval.val = int(c) - '0'
		return DIGIT
	} else if unicode.IsLower(c) {
		lval.val = int(c) - 'a'
		return LETTER
	}
	return int(c)
}

func (l *CalcLex) Error(s string) {
	fmt.Printf("syntax error: %s\n", s)
}

func main() {
	fi := bufio.NewReader(os.NewFile(0, "stdin"))

	for {
		var eqn string
		var ok bool

		fmt.Printf("equation: ")
		if eqn, ok = readline(fi); ok {
			CalcParse(&CalcLex{s: eqn})
		} else {
			break
		}
	}
}

func readline(fi *bufio.Reader) (string, bool) {
	s, err := fi.ReadString('\n')
	if err != nil {
		return "", false
	}
	return s, true
}

//line yacctab:1
var CalcExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const CalcPrivate = 57344

const CalcLast = 117

var CalcAct = [...]int8{
	9, 42, 56, 10, 60, 58, 5, 59, 57, 29,
	20, 19, 14, 15, 16, 17, 18, 11, 24, 3,
	73, 66, 7, 49, 10, 48, 23, 26, 41, 44,
	68, 6, 53, 72, 33, 34, 35, 36, 37, 38,
	39, 40, 11, 24, 71, 29, 55, 7, 29, 70,
	69, 62, 11, 4, 25, 29, 6, 7, 50, 32,
	65, 67, 31, 28, 8, 29, 6, 29, 11, 51,
	11, 27, 47, 20, 19, 14, 15, 16, 17, 18,
	64, 51, 54, 11, 27, 19, 14, 15, 16, 17,
	18, 13, 52, 22, 63, 28, 14, 15, 16, 17,
	18, 21, 16, 17, 18, 11, 63, 11, 61, 11,
	30, 2, 1, 46, 43, 45, 12,
}

var CalcPact = [...]int16{
	48, -1000, 77, 67, 86, 85, 38, 38, 79, 106,
	-1000, -1000, 42, -1000, 38, 38, 38, 38, 38, 38,
	38, 13, 56, 4, -1000, 47, -1000, 41, 76, 106,
	-1000, 105, -1000, 92, 92, -1000, -1000, -1000, 88, 78,
	67, 85, -1000, -1000, 66, -12, -13, 103, -1000, -1000,
	-1000, 34, 89, 106, 64, -1000, -1000, 5, -1000, 14,
	-1000, 33, 32, 27, 101, -1000, 105, -1000, 5, -1000,
	-1000, 16, 3, -1000,
}

var CalcPgo = [...]int8{
	0, 19, 0, 6, 2, 116, 1, 115, 114, 113,
	112, 111,
}

var CalcR1 = [...]int8{
	0, 10, 10, 11, 11, 11, 11, 11, 11, 3,
	3, 3, 3, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 9, 9, 8, 7,
	7, 6, 5, 5, 4, 2, 2,
}

var CalcR2 = [...]int8{
	0, 0, 2, 1, 3, 1, 3, 3, 3, 3,
	1, 5, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 2, 1, 5, 7, 1, 2, 3, 2, 2,
	3, 2, 2, 3, 2, 1, 2,
}

var CalcChk = [...]int16{
	-1000, -10, -11, -1, 5, -3, 18, 9, 16, -2,
	-4, 4, -5, 14, 8, 9, 10, 11, 12, 7,
	6, 15, 8, -1, 5, 16, -1, 5, 16, -2,
	4, 20, 17, -1, -1, -1, -1, -1, -1, -1,
	-1, -3, -6, -8, 16, -7, -9, 16, -4, 19,
	17, 5, 16, -2, 16, -6, -4, 20, 17, 20,
	17, 5, 17, 5, 16, -4, 16, -6, 16, 17,
	17, 17, 17, 17,
}

var CalcDef = [...]int8{
	1, -2, 0, 3, 22, 5, 0, 0, 0, 25,
	10, 35, 0, 2, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 22, 0, 21, 0, 0, 32,
	36, 0, 34, 14, 15, 16, 17, 18, 19, 20,
	4, 6, 7, 8, 0, 0, 0, 0, 12, 13,
	9, 0, 0, 33, 0, 26, 29, 0, 31, 0,
	28, 0, 0, 0, 0, 30, 0, 27, 0, 11,
	23, 0, 0, 24,
}

var CalcTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	14, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 12, 7, 3,
	18, 19, 10, 8, 20, 9, 3, 11, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 15, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 16, 3, 17, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 6,
}

var CalcTok2 = [...]int8{
	2, 3, 4, 5, 13,
}

var CalcTok3 = [...]int8{
	0,
}

var CalcErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	CalcDebug        = 0
	CalcErrorVerbose = false
)

type CalcLexer interface {
	Lex(lval *CalcSymType) int
	Error(s string)
}

type CalcParser interface {
	Parse(CalcLexer) int
	Lookahead() int
}

type CalcParserImpl struct {
	lval  CalcSymType
	stack [CalcInitialStackSize]CalcSymType
	char  int
}

func (p *CalcParserImpl) Lookahead() int {
	return p.char
}

func CalcNewParser() CalcParser {
	return &CalcParserImpl{}
}

const CalcFlag = -1000

func CalcTokname(c int) string {
	if c >= 1 && c-1 < len(CalcToknames) {
		if CalcToknames[c-1] != "" {
			return CalcToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func CalcStatname(s int) string {
	if s >= 0 && s < len(CalcStatenames) {
		if CalcStatenames[s] != "" {
			return CalcStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func CalcErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !CalcErrorVerbose {
		return "syntax error"
	}

	for _, e := range CalcErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + CalcTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(CalcPact[state])
	for tok := TOKSTART; tok-1 < len(CalcToknames); tok++ {
		if n := base + tok; n >= 0 && n < CalcLast && int(CalcChk[int(CalcAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if CalcDef[state] == -2 {
		i := 0
		for CalcExca[i] != -1 || int(CalcExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; CalcExca[i] >= 0; i += 2 {
			tok := int(CalcExca[i])
			if tok < TOKSTART || CalcExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if CalcExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += CalcTokname(tok)
	}
	return res
}

func Calclex1(lex CalcLexer, lval *CalcSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(CalcTok1[0])
		goto out
	}
	if char < len(CalcTok1) {
		token = int(CalcTok1[char])
		goto out
	}
	if char >= CalcPrivate {
		if char < CalcPrivate+len(CalcTok2) {
			token = int(CalcTok2[char-CalcPrivate])
			goto out
		}
	}
	for i := 0; i < len(CalcTok3); i += 2 {
		token = int(CalcTok3[i+0])
		if token == char {
			token = int(CalcTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(CalcTok2[1]) /* unknown char */
	}
	if CalcDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", CalcTokname(token), uint(char))
	}
	return char, token
}

func CalcParse(Calclex CalcLexer) int {
	return CalcNewParser().Parse(Calclex)
}

func (Calcrcvr *CalcParserImpl) Parse(Calclex CalcLexer) int {
	var Calcn int
	var CalcVAL CalcSymType
	var CalcDollar []CalcSymType
	_ = CalcDollar // silence set and not used
	CalcS := Calcrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Calcstate := 0
	Calcrcvr.char = -1
	Calctoken := -1 // Calcrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Calcstate = -1
		Calcrcvr.char = -1
		Calctoken = -1
	}()
	Calcp := -1
	goto Calcstack

ret0:
	return 0

ret1:
	return 1

Calcstack:
	/* put a state and value onto the stack */
	if CalcDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", CalcTokname(Calctoken), CalcStatname(Calcstate))
	}

	Calcp++
	if Calcp >= len(CalcS) {
		nyys := make([]CalcSymType, len(CalcS)*2)
		copy(nyys, CalcS)
		CalcS = nyys
	}
	CalcS[Calcp] = CalcVAL
	CalcS[Calcp].yys = Calcstate

Calcnewstate:
	Calcn = int(CalcPact[Calcstate])
	if Calcn <= CalcFlag {
		goto Calcdefault /* simple state */
	}
	if Calcrcvr.char < 0 {
		Calcrcvr.char, Calctoken = Calclex1(Calclex, &Calcrcvr.lval)
	}
	Calcn += Calctoken
	if Calcn < 0 || Calcn >= CalcLast {
		goto Calcdefault
	}
	Calcn = int(CalcAct[Calcn])
	if int(CalcChk[Calcn]) == Calctoken { /* valid shift */
		Calcrcvr.char = -1
		Calctoken = -1
		CalcVAL = Calcrcvr.lval
		Calcstate = Calcn
		if Errflag > 0 {
			Errflag--
		}
		goto Calcstack
	}

Calcdefault:
	/* default state action */
	Calcn = int(CalcDef[Calcstate])
	if Calcn == -2 {
		if Calcrcvr.char < 0 {
			Calcrcvr.char, Calctoken = Calclex1(Calclex, &Calcrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if CalcExca[xi+0] == -1 && int(CalcExca[xi+1]) == Calcstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Calcn = int(CalcExca[xi+0])
			if Calcn < 0 || Calcn == Calctoken {
				break
			}
		}
		Calcn = int(CalcExca[xi+1])
		if Calcn < 0 {
			goto ret0
		}
	}
	if Calcn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Calclex.Error(CalcErrorMessage(Calcstate, Calctoken))
			Nerrs++
			if CalcDebug >= 1 {
				__yyfmt__.Printf("%s", CalcStatname(Calcstate))
				__yyfmt__.Printf(" saw %s\n", CalcTokname(Calctoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Calcp >= 0 {
				Calcn = int(CalcPact[CalcS[Calcp].yys]) + CalcErrCode
				if Calcn >= 0 && Calcn < CalcLast {
					Calcstate = int(CalcAct[Calcn]) /* simulate a shift of "error" */
					if int(CalcChk[Calcstate]) == CalcErrCode {
						goto Calcstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if CalcDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", CalcS[Calcp].yys)
				}
				Calcp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if CalcDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", CalcTokname(Calctoken))
			}
			if Calctoken == CalcEofCode {
				goto ret1
			}
			Calcrcvr.char = -1
			Calctoken = -1
			goto Calcnewstate /* try again in the same state */
		}
	}

	/* reduction by production Calcn */
	if CalcDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Calcn, CalcStatname(Calcstate))
	}

	Calcnt := Calcn
	Calcpt := Calcp
	_ = Calcpt // guard against "declared and not used"

	Calcp -= int(CalcR2[Calcn])
	// Calcp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Calcp+1 >= len(CalcS) {
		nyys := make([]CalcSymType, len(CalcS)*2)
		copy(nyys, CalcS)
		CalcS = nyys
	}
	CalcVAL = CalcS[Calcp+1]

	/* consult goto table to find next state */
	Calcn = int(CalcR1[Calcn])
	Calcg := int(CalcPgo[Calcn])
	Calcj := Calcg + CalcS[Calcp].yys + 1

	if Calcj >= CalcLast {
		Calcstate = int(CalcAct[Calcg])
	} else {
		Calcstate = int(CalcAct[Calcj])
		if int(CalcChk[Calcstate]) != -Calcn {
			Calcstate = int(CalcAct[Calcg])
		}
	}
	// dummy call; replaced with literal code
	switch Calcnt {

	case 4:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:68
		{
			regs[CalcDollar[1].val] = CalcDollar[3].val
		}
	case 6:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:73
		{
			arrayMap[CalcDollar[1].val] = CalcDollar[3].slice
		}
	case 7:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:77
		{
			arrayMap2[CalcDollar[1].val] = CalcDollar[3].twoDslice
		}
	case 8:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:81
		{
			arrayMap3[CalcDollar[1].val] = CalcDollar[3].threeDslice
		}
	case 9:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:87
		{
			fmt.Println(arrayMap[CalcDollar[2].val])
		}
	case 10:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:89
		{
			CalcVAL.slice = CalcDollar[1].slice
		}
	case 11:
		CalcDollar = CalcS[Calcpt-5 : Calcpt+1]
//line calc.y:91
		{
			CalcVAL.slice = make([]int, len(CalcDollar[1].slice))
			for i := 0; i < len(CalcDollar[1].slice); i++ {
				CalcVAL.slice[i] = CalcDollar[1].slice[i] + arrayMap[CalcDollar[4].val][i]
			}
		}
	case 12:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:98
		{
			CalcVAL.slice = make([]int, len(CalcDollar[1].slice))
			for i := 0; i < len(CalcDollar[1].slice); i++ {
				CalcVAL.slice[i] = CalcDollar[1].slice[i] + CalcDollar[3].slice[i]
			}
		}
	case 13:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:107
		{
			CalcVAL.val = CalcDollar[2].val
		}
	case 14:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:109
		{
			CalcVAL.val = CalcDollar[1].val + CalcDollar[3].val
		}
	case 15:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:111
		{
			CalcVAL.val = CalcDollar[1].val - CalcDollar[3].val
		}
	case 16:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:113
		{
			CalcVAL.val = CalcDollar[1].val * CalcDollar[3].val
		}
	case 17:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:115
		{
			CalcVAL.val = CalcDollar[1].val / CalcDollar[3].val
		}
	case 18:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:117
		{
			CalcVAL.val = CalcDollar[1].val % CalcDollar[3].val
		}
	case 19:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:119
		{
			CalcVAL.val = CalcDollar[1].val & CalcDollar[3].val
		}
	case 20:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:121
		{
			CalcVAL.val = CalcDollar[1].val | CalcDollar[3].val
		}
	case 21:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:123
		{
			CalcVAL.val = -CalcDollar[2].val
		}
	case 22:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:125
		{
			fmt.Println(regs[CalcDollar[1].val])
		}
	case 23:
		CalcDollar = CalcS[Calcpt-5 : Calcpt+1]
//line calc.y:127
		{
			fmt.Println(arrayMap2[CalcDollar[3].val])
		}
	case 24:
		CalcDollar = CalcS[Calcpt-7 : Calcpt+1]
//line calc.y:129
		{
			fmt.Println(arrayMap3[CalcDollar[4].val])
		}
	case 26:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:135
		{
			CalcVAL.threeDslice = append(CalcVAL.threeDslice, CalcDollar[2].twoDslice)
		}
	case 27:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:137
		{
			CalcVAL.threeDslice = append(CalcVAL.threeDslice, CalcDollar[3].twoDslice)
		}
	case 28:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:140
		{
			CalcVAL.threeDslice = CalcDollar[1].threeDslice
		}
	case 29:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:145
		{
			CalcVAL.twoDslice = append(CalcVAL.twoDslice, CalcDollar[2].slice)
		}
	case 30:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:147
		{
			CalcVAL.twoDslice = append(CalcVAL.twoDslice, CalcDollar[3].slice)
		}
	case 31:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:150
		{
			CalcVAL.twoDslice = CalcDollar[1].twoDslice
		}
	case 32:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:155
		{
			CalcVAL.slice = append(CalcVAL.slice, CalcDollar[2].val)
		}
	case 33:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:157
		{
			CalcVAL.slice = append(CalcVAL.slice, CalcDollar[3].val)
		}
	case 34:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:160
		{
			CalcVAL.slice = CalcDollar[1].slice
		}
	case 35:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:165
		{
			CalcVAL.val = CalcDollar[1].val
			if CalcDollar[1].val == 0 {
				base = 8
			} else {
				base = 10
			}
		}
	case 36:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:174
		{
			CalcVAL.val = base*CalcDollar[1].val + CalcDollar[2].val
		}
	}
	goto Calcstack /* stack new state and value */
}
