// Code generated by goyacc -o calc.go -p Calc calc.y. DO NOT EDIT.

//line calc.y:8

package main

import __yyfmt__ "fmt"

//line calc.y:9

import (
	"bufio"
	"fmt"
	"os"
	"unicode"
)

// a number
var regs = make([]int, 26)

// one dimensional
var arrayMap = make(map[int][]int)

// two dimensionals
var arrayMap2 = make(map[int][][]int)

// temporary
var tmp = []int{}
var tmp1 = []int{}
var tmp2 = [][]int{}
var base int

//line calc.y:37
type CalcSymType struct {
	yys int
	val int
}

const DIGIT = 57346
const LETTER = 57347
const UMINUS = 57348

var CalcToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"DIGIT",
	"LETTER",
	"'|'",
	"'&'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UMINUS",
	"'\\n'",
	"'='",
	"'('",
	"')'",
	"'['",
	"']'",
	"','",
}

var CalcStatenames = [...]string{}

const CalcEofCode = 1
const CalcErrCode = 2
const CalcInitialStackSize = 16

//line calc.y:137
/*  start  of  programs  */

type CalcLex struct {
	s   string
	pos int
}

func (l *CalcLex) Lex(lval *CalcSymType) int {
	var c rune = ' '
	for c == ' ' {
		if l.pos == len(l.s) {
			return 0
		}
		c = rune(l.s[l.pos])
		l.pos += 1
	}

	if unicode.IsDigit(c) {
		lval.val = int(c) - '0'
		return DIGIT
	} else if unicode.IsLower(c) {
		lval.val = int(c) - 'a'
		return LETTER
	}
	return int(c)
}

func (l *CalcLex) Error(s string) {
	fmt.Printf("syntax error: %s\n", s)
}

func main() {
	fi := bufio.NewReader(os.NewFile(0, "stdin"))

	for {
		var eqn string
		var ok bool

		fmt.Printf("equation: ")
		if eqn, ok = readline(fi); ok {
			CalcParse(&CalcLex{s: eqn})
		} else {
			break
		}
	}
}

func readline(fi *bufio.Reader) (string, bool) {
	s, err := fi.ReadString('\n')
	if err != nil {
		return "", false
	}
	return s, true
}

//line yacctab:1
var CalcExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const CalcPrivate = 57344

const CalcLast = 94

var CalcAct = [...]int8{
	8, 3, 33, 48, 45, 47, 51, 19, 21, 49,
	50, 53, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 17, 16, 11, 12, 13, 14, 15, 52, 44,
	9, 20, 36, 37, 48, 6, 43, 18, 42, 10,
	43, 22, 5, 46, 35, 9, 38, 9, 20, 43,
	54, 55, 6, 56, 23, 9, 4, 9, 22, 5,
	6, 7, 11, 12, 13, 14, 15, 5, 38, 7,
	40, 39, 17, 16, 11, 12, 13, 14, 15, 16,
	11, 12, 13, 14, 15, 13, 14, 15, 24, 9,
	34, 2, 1, 41,
}

var CalcPact = [...]int16{
	51, -1000, 25, 66, 22, 43, 43, 36, 84, -1000,
	-1000, 43, 43, 43, 43, 43, 43, 43, 26, 15,
	-1000, -1000, 14, 63, -1000, 75, 75, -1000, -1000, -1000,
	54, 72, 66, -1000, -1000, 53, -1000, -1000, 10, 41,
	-15, -10, -14, 8, -8, -1000, -1000, 16, 85, -1000,
	85, -1000, 85, -1000, -1000, 84, 84,
}

var CalcPgo = [...]int8{
	0, 1, 0, 93, 92, 91, 2, 90, 70,
}

var CalcR1 = [...]int8{
	0, 4, 4, 5, 5, 5, 5, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	7, 8, 8, 8, 6, 3, 3, 2, 2,
}

var CalcR2 = [...]int8{
	0, 0, 2, 1, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 2, 1, 3, 5, 1,
	3, 2, 3, 2, 3, 3, 3, 1, 2,
}

var CalcChk = [...]int16{
	-1000, -4, -5, -1, 5, 16, 9, 18, -2, 4,
	14, 8, 9, 10, 11, 12, 7, 6, 15, -1,
	5, -1, 5, 18, 4, -1, -1, -1, -1, -1,
	-1, -1, -1, -6, -7, 18, 17, 19, 5, 18,
	-8, -3, -6, -2, 19, 19, -6, 20, 18, 19,
	20, 20, 20, 19, -6, -2, -2,
}

var CalcDef = [...]int8{
	1, -2, 0, 3, 16, 0, 0, 0, 19, 27,
	2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	16, 15, 0, 0, 28, 8, 9, 10, 11, 12,
	13, 14, 4, 5, 6, 0, 7, 17, 0, 0,
	0, 0, 0, 0, 0, 20, 21, 0, 0, 24,
	0, 23, 0, 18, 22, 25, 26,
}

var CalcTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	14, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 12, 7, 3,
	16, 17, 10, 8, 20, 9, 3, 11, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 15, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 18, 3, 19, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 6,
}

var CalcTok2 = [...]int8{
	2, 3, 4, 5, 13,
}

var CalcTok3 = [...]int8{
	0,
}

var CalcErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	CalcDebug        = 0
	CalcErrorVerbose = false
)

type CalcLexer interface {
	Lex(lval *CalcSymType) int
	Error(s string)
}

type CalcParser interface {
	Parse(CalcLexer) int
	Lookahead() int
}

type CalcParserImpl struct {
	lval  CalcSymType
	stack [CalcInitialStackSize]CalcSymType
	char  int
}

func (p *CalcParserImpl) Lookahead() int {
	return p.char
}

func CalcNewParser() CalcParser {
	return &CalcParserImpl{}
}

const CalcFlag = -1000

func CalcTokname(c int) string {
	if c >= 1 && c-1 < len(CalcToknames) {
		if CalcToknames[c-1] != "" {
			return CalcToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func CalcStatname(s int) string {
	if s >= 0 && s < len(CalcStatenames) {
		if CalcStatenames[s] != "" {
			return CalcStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func CalcErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !CalcErrorVerbose {
		return "syntax error"
	}

	for _, e := range CalcErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + CalcTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(CalcPact[state])
	for tok := TOKSTART; tok-1 < len(CalcToknames); tok++ {
		if n := base + tok; n >= 0 && n < CalcLast && int(CalcChk[int(CalcAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if CalcDef[state] == -2 {
		i := 0
		for CalcExca[i] != -1 || int(CalcExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; CalcExca[i] >= 0; i += 2 {
			tok := int(CalcExca[i])
			if tok < TOKSTART || CalcExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if CalcExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += CalcTokname(tok)
	}
	return res
}

func Calclex1(lex CalcLexer, lval *CalcSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(CalcTok1[0])
		goto out
	}
	if char < len(CalcTok1) {
		token = int(CalcTok1[char])
		goto out
	}
	if char >= CalcPrivate {
		if char < CalcPrivate+len(CalcTok2) {
			token = int(CalcTok2[char-CalcPrivate])
			goto out
		}
	}
	for i := 0; i < len(CalcTok3); i += 2 {
		token = int(CalcTok3[i+0])
		if token == char {
			token = int(CalcTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(CalcTok2[1]) /* unknown char */
	}
	if CalcDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", CalcTokname(token), uint(char))
	}
	return char, token
}

func CalcParse(Calclex CalcLexer) int {
	return CalcNewParser().Parse(Calclex)
}

func (Calcrcvr *CalcParserImpl) Parse(Calclex CalcLexer) int {
	var Calcn int
	var CalcVAL CalcSymType
	var CalcDollar []CalcSymType
	_ = CalcDollar // silence set and not used
	CalcS := Calcrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Calcstate := 0
	Calcrcvr.char = -1
	Calctoken := -1 // Calcrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Calcstate = -1
		Calcrcvr.char = -1
		Calctoken = -1
	}()
	Calcp := -1
	goto Calcstack

ret0:
	return 0

ret1:
	return 1

Calcstack:
	/* put a state and value onto the stack */
	if CalcDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", CalcTokname(Calctoken), CalcStatname(Calcstate))
	}

	Calcp++
	if Calcp >= len(CalcS) {
		nyys := make([]CalcSymType, len(CalcS)*2)
		copy(nyys, CalcS)
		CalcS = nyys
	}
	CalcS[Calcp] = CalcVAL
	CalcS[Calcp].yys = Calcstate

Calcnewstate:
	Calcn = int(CalcPact[Calcstate])
	if Calcn <= CalcFlag {
		goto Calcdefault /* simple state */
	}
	if Calcrcvr.char < 0 {
		Calcrcvr.char, Calctoken = Calclex1(Calclex, &Calcrcvr.lval)
	}
	Calcn += Calctoken
	if Calcn < 0 || Calcn >= CalcLast {
		goto Calcdefault
	}
	Calcn = int(CalcAct[Calcn])
	if int(CalcChk[Calcn]) == Calctoken { /* valid shift */
		Calcrcvr.char = -1
		Calctoken = -1
		CalcVAL = Calcrcvr.lval
		Calcstate = Calcn
		if Errflag > 0 {
			Errflag--
		}
		goto Calcstack
	}

Calcdefault:
	/* default state action */
	Calcn = int(CalcDef[Calcstate])
	if Calcn == -2 {
		if Calcrcvr.char < 0 {
			Calcrcvr.char, Calctoken = Calclex1(Calclex, &Calcrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if CalcExca[xi+0] == -1 && int(CalcExca[xi+1]) == Calcstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Calcn = int(CalcExca[xi+0])
			if Calcn < 0 || Calcn == Calctoken {
				break
			}
		}
		Calcn = int(CalcExca[xi+1])
		if Calcn < 0 {
			goto ret0
		}
	}
	if Calcn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Calclex.Error(CalcErrorMessage(Calcstate, Calctoken))
			Nerrs++
			if CalcDebug >= 1 {
				__yyfmt__.Printf("%s", CalcStatname(Calcstate))
				__yyfmt__.Printf(" saw %s\n", CalcTokname(Calctoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Calcp >= 0 {
				Calcn = int(CalcPact[CalcS[Calcp].yys]) + CalcErrCode
				if Calcn >= 0 && Calcn < CalcLast {
					Calcstate = int(CalcAct[Calcn]) /* simulate a shift of "error" */
					if int(CalcChk[Calcstate]) == CalcErrCode {
						goto Calcstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if CalcDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", CalcS[Calcp].yys)
				}
				Calcp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if CalcDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", CalcTokname(Calctoken))
			}
			if Calctoken == CalcEofCode {
				goto ret1
			}
			Calcrcvr.char = -1
			Calctoken = -1
			goto Calcnewstate /* try again in the same state */
		}
	}

	/* reduction by production Calcn */
	if CalcDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Calcn, CalcStatname(Calcstate))
	}

	Calcnt := Calcn
	Calcpt := Calcp
	_ = Calcpt // guard against "declared and not used"

	Calcp -= int(CalcR2[Calcn])
	// Calcp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Calcp+1 >= len(CalcS) {
		nyys := make([]CalcSymType, len(CalcS)*2)
		copy(nyys, CalcS)
		CalcS = nyys
	}
	CalcVAL = CalcS[Calcp+1]

	/* consult goto table to find next state */
	Calcn = int(CalcR1[Calcn])
	Calcg := int(CalcPgo[Calcn])
	Calcj := Calcg + CalcS[Calcp].yys + 1

	if Calcj >= CalcLast {
		Calcstate = int(CalcAct[Calcg])
	} else {
		Calcstate = int(CalcAct[Calcj])
		if int(CalcChk[Calcstate]) != -Calcn {
			Calcstate = int(CalcAct[Calcg])
		}
	}
	// dummy call; replaced with literal code
	switch Calcnt {

	case 4:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:62
		{
			regs[CalcDollar[1].val] = CalcDollar[3].val
		}
	case 5:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:66
		{
			arrayMap[CalcDollar[1].val] = tmp
		}
	case 6:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:70
		{
			arrayMap2[CalcDollar[1].val] = tmp2
		}
	case 7:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:76
		{
			CalcVAL.val = CalcDollar[2].val
		}
	case 8:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:78
		{
			CalcVAL.val = CalcDollar[1].val + CalcDollar[3].val
		}
	case 9:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:80
		{
			CalcVAL.val = CalcDollar[1].val - CalcDollar[3].val
		}
	case 10:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:82
		{
			CalcVAL.val = CalcDollar[1].val * CalcDollar[3].val
		}
	case 11:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:84
		{
			CalcVAL.val = CalcDollar[1].val / CalcDollar[3].val
		}
	case 12:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:86
		{
			CalcVAL.val = CalcDollar[1].val % CalcDollar[3].val
		}
	case 13:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:88
		{
			CalcVAL.val = CalcDollar[1].val & CalcDollar[3].val
		}
	case 14:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:90
		{
			CalcVAL.val = CalcDollar[1].val | CalcDollar[3].val
		}
	case 15:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:92
		{
			CalcVAL.val = -CalcDollar[2].val
		}
	case 16:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:94
		{
			fmt.Println(regs[CalcDollar[1].val])
		}
	case 17:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:96
		{
			fmt.Println(arrayMap[CalcDollar[2].val])
		}
	case 18:
		CalcDollar = CalcS[Calcpt-5 : Calcpt+1]
//line calc.y:98
		{
			fmt.Println(arrayMap2[CalcDollar[3].val])
		}
	case 21:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:106
		{
			tmp2 = append(tmp2, tmp1)
			tmp1 = []int{}
			fmt.Println("1 >>>>>")
		}
	case 22:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:108
		{
			tmp2 = append(tmp2, tmp1)
			tmp1 = []int{}
			fmt.Println("2 >>>>>")
		}
	case 23:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:110
		{
			tmp2 = append(tmp2, tmp1)
			tmp1 = []int{}
			fmt.Println("3 >>>>>")
		}
	case 24:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:114
		{
			tmp1 = tmp
			tmp = []int{}
		}
	case 25:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:118
		{
			tmp = append(tmp, CalcDollar[3].val)
		}
	case 26:
		CalcDollar = CalcS[Calcpt-3 : Calcpt+1]
//line calc.y:120
		{
			tmp = append(tmp, CalcDollar[1].val, CalcDollar[3].val)
		}
	case 27:
		CalcDollar = CalcS[Calcpt-1 : Calcpt+1]
//line calc.y:125
		{
			CalcVAL.val = CalcDollar[1].val
			if CalcDollar[1].val == 0 {
				base = 8
			} else {
				base = 10
			}
		}
	case 28:
		CalcDollar = CalcS[Calcpt-2 : Calcpt+1]
//line calc.y:134
		{
			CalcVAL.val = base*CalcDollar[1].val + CalcDollar[2].val
		}
	}
	goto Calcstack /* stack new state and value */
}
